server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    large_client_header_buffers 4 32k;
    client_header_buffer_size 16k;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
